@startuml

package Domain {
  class Training {
      - id: String
      - status: TrainingStatus
      - type: TrainingType
      - size: Integer
      - tags: List<String>
      - createdAt: LocalDateTime
      - completedAt: LocalDateTime
      - trainingSession: TrainingSession

      + complete(): TrainingDomainEvent
  }

  class TrainingSession {
      - words: List<Word>
      - wordsForRepetition: List<Word>
      - approvedWords: List<Word>

      + shuffle(): void
  }

  class TrainingService {
      + getSimpleTrainingByTags(List<String> tags): Training
      + getSimpleRandomTraining(int size): Training
      + getSimpleRepeatTraining(int size): Training
  }

  class TrainingDomainEvent {
      - NAME: String
      - training: Training
  }

  interface TrainingRepository {
  }
}

package Application {
  class TrainingFinisher {
    finishTrainingSession(FinishTrainingDto trainingData): void
  }

  class TrainingProvider {
    + getTraining(TrainingType type, List<String> tags, Integer size): Training
  }
}

package Infrastructure {
  interface TrainingSpringRepository {
  }
  class TrainingEntity{
  }
  class TrainingEntityMapper{
  }
  class TrainingRepositoryImpl{
  }
}

package Presentation {
  class FileTrainingController {
    + getTraining(List<String> tags): FileTraining
    + finish(FinishTrainingDto training): void
  }

  class TrainingController {
    + get(List<String> tags,TrainingType type,Integer size): Training
  }

  class FinishTrainingDto {
      - id: String
      - words: List<String>
      - wordsForRepetition: List<String>
      - approvedWords: List<String>
  }

  class FileTraining {
    - file: InputStream
    - name: String
    - fileSize: int
    - fileExtension: String
  }

  class TrainingToCsvFileBuilder{
    + build(String name, Training training): FileTraining
  }
}

TrainingProvider o-- TrainingService
TrainingProvider o-- TrainingRepository
TrainingFinisher o-- TrainingRepository
TrainingRepositoryImpl --|> TrainingRepository
TrainingRepositoryImpl --|> TrainingSpringRepository
TrainingRepositoryImpl o-- TrainingEntityMapper
FileTrainingController o-- TrainingProvider
FileTrainingController o-- TrainingToCsvFileBuilder
TrainingController o-- TrainingProvider
Training *-- TrainingSession

@enduml
