listen:
  port: 4040
  address: "{{ app_host_address }}"
  metrics_endpoint: "/metrics"

namespaces:
  - name: nginx
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" rt=$request_time urt=$upstream_response_time"
    source:
      files:
        - /var/log/nginx/access.log
    labels:
      app: "nginx-host-metrics"
      environment: "production"
      foo: "bar"
    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]